// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn3TwZmD1ocoJaD-JHHPeklD_LA3B9Uno',
    appId: '1:847008847185:web:96531a20cf25e9a8c32f70',
    messagingSenderId: '847008847185',
    projectId: 'isread-app',
    authDomain: 'isread-app.firebaseapp.com',
    storageBucket: 'isread-app.firebasestorage.app',
    measurementId: 'G-1HJREQ9CSY',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWnXLzfzXVqKgefiDZTZ3O8eAeQ9_qbcA',
    appId: '1:847008847185:ios:7083fb95c48cac39c32f70',
    messagingSenderId: '847008847185',
    projectId: 'isread-app',
    storageBucket: 'isread-app.firebasestorage.app',
    iosBundleId: 'com.example.isread',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWnXLzfzXVqKgefiDZTZ3O8eAeQ9_qbcA',
    appId: '1:847008847185:ios:7083fb95c48cac39c32f70',
    messagingSenderId: '847008847185',
    projectId: 'isread-app',
    storageBucket: 'isread-app.firebasestorage.app',
    iosBundleId: 'com.example.isread',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVGlarkHaH2BVrqDAEHSyJ7pt8IeuES5E',
    appId: '1:847008847185:android:e0660617a58e97f2c32f70',
    messagingSenderId: '847008847185',
    projectId: 'isread-app',
    storageBucket: 'isread-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn3TwZmD1ocoJaD-JHHPeklD_LA3B9Uno',
    appId: '1:847008847185:web:5c32ea16391f599fc32f70',
    messagingSenderId: '847008847185',
    projectId: 'isread-app',
    authDomain: 'isread-app.firebaseapp.com',
    storageBucket: 'isread-app.firebasestorage.app',
    measurementId: 'G-M0WEPT1ZSJ',
  );

}